import numpy
from numpy import int16
from typing import overload, Sequence


class ValueEncoder:
    def __init__(self: ValueEncoder) -> None: ...
    @property
    def classes_(self: ValueEncoder) -> str: ...
    def fit(self: ValueEncoder, characters: str) -> ValueEncoder: ...
    @overload
    def transform(self: ValueEncoder, value: str, cap: bool = False) -> numpy.ndarray[int16]: ...
    @overload
    def transform(self: ValueEncoder, values: Sequence[str], missing_value: int = -1, cap: bool = False) -> numpy.ndarray[int16]: ...
    def inverse_transform(self: ValueEncoder, value: numpy.ndarray[int16]) -> str: ...
